### ISSUE TITLE
HTML comments shouldn't be parsed when pre-compiling templates

### ISSUE THREAD

**Issue by sidonath** [tchak/barber#14]
I'm using ember-rails to precompile Handlebars templates for our Ember.js app and noticed that HTML comments are being parsed in templates.

This causes Ember to throw the following error if Handlebars tags are present in a comment: "Cannot perform operations on a Metamorph that is not in the DOM."

Here's a snippet from a precompiled template:

```javascript
data.buffer.push("<!-- ");
hashTypes = {};
stack1 = helpers['if'].call(depth0, "open", {hash:{},inverse:self.program(5, program5, data),fn:self.program(3, program3, data),contexts:[depth0],types:["ID"],hashTypes:hashTypes,data:data});
if(stack1 || stack1 === 0) { data.buffer.push(stack1); }
data.buffer.push(" -->\n");
```

The expected output would be to have the whole comment pushed verbatim to the buffer.

Thanks!

**Comment by tchak** [comment]
This is not a barber issue. This just how handlebars work. If you want comments in handlebars, you should use `{{! }}`.
