### ISSUE TITLE
Handlebars 1.1.2

### ISSUE THREAD

**Issue by josepjaume** [tchak/barber#22]
Hi!

Is there anything preventing barber to use handlebars 1.1.2? I think I have a bug in my ember.js application that may be solved by updating handlebars, but I can't since I depend on `ember-rails`, which depends on `barber`.

If there's no compelling reason, may I send some PR's to those projects? (knowing that @tchak maintains both of them).

Thanks!

**Comment by tricknotes** [comment]
I think this is solved on master.
So I close this issue.
