### ISSUE TITLE
Now it is hardly what supporting both Ember.js and raw Handlebars

### ISSUE THREAD

**Issue by tricknotes** [tchak/barber#34]
barber is awesome project for Handlebars precompilation in Ruby world.

Otherwise, Ember.js 1.10.0 uses HTMLBars instead of Handlebars.
So it makes hardly to maintain both supporting compilation for Ember.js and raw Handlebars. (such as https://github.com/tchak/barber/pull/33 )

@tchak 
If you don't mind, could you consider extracting  Emebr specific code from barber?
(or make barber Ember specific compiler.)

If you would agree with me, I'll work for it .

**Comment by tchak** [comment]
I have no real opinion on this. I have not used ruby stuff for building js in years :) So, go ahead, do what seems best for community :)

**Comment by tricknotes** [comment]
Thanks dude!
Then I'll make barber Ember specific bit by bit :-)

Would you mind adding me to a rubygem's collaborator?
My account is [tricknotes](https://rubygems.org/profiles/tricknotes).

**Comment by tricknotes** [comment]
> Would you mind adding me to a rubygem's collaborator?

@tchak It this OK?

**Comment by tricknotes** [comment]
Thanks. 
I can release now.
